# Generated by Django 5.0.12 on 2026-07-28 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('scope', models.CharField(choices=[('all', 'All Users'), ('patient', 'All Patients'), ('doctor', 'All Doctors'), ('secretary', 'All Secretaries')], default='all', max_length=20)),
                ('override_opt_out', models.BooleanField(default=False, help_text='Also email users who disabled email notifications (use only for urgent/critical announcements).')),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('email_sent_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='broadcast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.broadcast'),
        ),
    ]
