# Generated by Django 5.1.9 on 2026-08-02 06:10

import django.db.models.deletion
from django.db import migrations, models


def backfill_vitals_appointment(apps, schema_editor):
    """Link existing vitals to their visit where unambiguous. A vital is
    linked only when the patient had exactly one appointment on date_taken;
    zero or multiple appointments leave it unlinked (it shows under "General
    Vitals" on the Patient Records page). No data is lost either way."""
    VitalSign = apps.get_model('records', 'VitalSign')
    Appointment = apps.get_model('appointments', 'Appointment')
    from collections import defaultdict

    patient_days = defaultdict(list)
    for v in VitalSign.objects.values_list('id', 'patient_id', 'date_taken'):
        patient_days[(v[1], v[2])].append(v[0])

    # Map (patient, date) -> single appointment id when unambiguous.
    date_to_appt = {}
    for (patient_id, date_taken), vital_ids in patient_days.items():
        appt_ids = list(
            Appointment.objects.filter(patient_id=patient_id, appointment_date=date_taken)
            .values_list('id', flat=True)
        )
        if len(appt_ids) == 1:
            date_to_appt[(patient_id, date_taken)] = appt_ids[0]

    for (patient_id, date_taken), vital_ids in patient_days.items():
        appt_id = date_to_appt.get((patient_id, date_taken))
        if appt_id:
            VitalSign.objects.filter(id__in=vital_ids).update(appointment_id=appt_id)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_alter_appointment_options'),
        ('records', '0002_prescription_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalsign',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vital_signs', to='appointments.appointment'),
        ),
        migrations.RunPython(backfill_vitals_appointment, noop_reverse),
    ]
