# Generated by Django 4.2.28 on 2026-06-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_email_notifications_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretaryprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='secretaryprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='Employee/Staff ID'),
        ),
    ]
