# Generated by Django 4.2.28 on 2026-06-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_secretaryprofile_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='terms_accepted_version',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
