# Generated by Django 5.0.12 on 2026-07-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_mark_existing_users_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(blank=True, choices=[('General Practitioner / Family Medicine Physician', 'General Practitioner / Family Medicine Physician'), ('Internist (Internal Medicine)', 'Internist (Internal Medicine)'), ('Pediatrician', 'Pediatrician'), ('Obstetrician-Gynecologist (OB-GYN)', 'Obstetrician-Gynecologist (OB-GYN)'), ('Surgeon (General Surgery)', 'Surgeon (General Surgery)'), ('Cardiologist', 'Cardiologist'), ('Neurologist', 'Neurologist'), ('Dermatologist', 'Dermatologist'), ('Psychiatrist', 'Psychiatrist'), ('Ophthalmologist', 'Ophthalmologist'), ('Otorhinolaryngologist (ENT)', 'Otorhinolaryngologist (ENT)'), ('Orthopedic Surgeon', 'Orthopedic Surgeon'), ('Urologist', 'Urologist'), ('Nephrologist', 'Nephrologist'), ('Endocrinologist', 'Endocrinologist'), ('Gastroenterologist', 'Gastroenterologist'), ('Pulmonologist', 'Pulmonologist'), ('Oncologist', 'Oncologist'), ('Radiologist', 'Radiologist'), ('Anesthesiologist', 'Anesthesiologist'), ('Pathologist', 'Pathologist'), ('Rheumatologist', 'Rheumatologist'), ('Hematologist', 'Hematologist'), ('Infectious Disease Specialist', 'Infectious Disease Specialist'), ('Allergist / Immunologist', 'Allergist / Immunologist'), ('Nutritionist-Dietitian', 'Nutritionist-Dietitian'), ('Physiatrist (Physical Medicine & Rehabilitation)', 'Physiatrist (Physical Medicine & Rehabilitation)'), ('Dentist', 'Dentist')], max_length=150),
        ),
    ]
