# Generated by Django 5.1.9 on 2026-08-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='allergies',
            field=models.TextField(blank=True, help_text='Known allergies (e.g. Penicillin, peanuts).'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='chronic_conditions',
            field=models.TextField(blank=True, help_text='Chronic conditions (e.g. Hypertension, Diabetes).'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='critical_notes',
            field=models.TextField(blank=True, help_text='Any other safety flags relevant to treatment.'),
        ),
    ]
