# Generated by Django 5.0.12 on 2026-08-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('auto_logout', 'Auto logout (inactivity)'), ('login_failed', 'Failed login'), ('password_change', 'Password changed'), ('account_deactivated', 'Account deactivated')], max_length=20),
        ),
    ]
