# Generated by Django 5.0.12 on 2026-08-02 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_activitylog_action'),
        ('accounts', '0014_patientprofile_allergies_and_more'),
    ]

    operations = [
    ]
