# Generated by Django 5.0.12 on 2026-08-06 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_customuser_email_otp_customuser_email_otp_attempts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretaryCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='covering_secretaries', to=settings.AUTH_USER_MODEL)),
                ('secretary', models.ForeignKey(limit_choices_to={'role': 'secretary'}, on_delete=django.db.models.deletion.CASCADE, related_name='coverage_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('secretary', 'doctor')},
            },
        ),
    ]
