from django.db import models
from django.db.models import F
from django.conf import settings
from django.utils import timezone

# SQLite sorts NULLs first in ascending order but Postgres sorts them last;
# appointments awaiting a time assignment (appointment_time IS NULL) must stay
# at the top of each date group on both backends.
TIME_NULLS_FIRST = F('appointment_time').asc(nulls_first=True)


class Schedule(models.Model):
    SOURCE_CHOICES = [
        ('manual',   'Manual'),
        ('template', 'Template'),
    ]

    doctor         = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='schedules', limit_choices_to={'role': 'doctor'}
    )
    specific_date  = models.DateField()
    start_time     = models.TimeField()
    end_time       = models.TimeField()
    # 'manual' = created/touched directly by a doctor or secretary through the
    # per-date tools (Add Slot / Add Time for This Day / Edit). 'template' =
    # materialized automatically from a ScheduleTemplate block by
    # services.sync_generated_schedule_for_doctor(). Only 'template' rows are
    # ever auto-created or auto-removed by the sync; 'manual' rows (and any
    # date with a ScheduleException) are never touched by it.
    source         = models.CharField(max_length=10, choices=SOURCE_CHOICES, default='manual')

    class Meta:
        unique_together = ('doctor', 'specific_date', 'start_time')
        ordering = ['specific_date', 'start_time']

    @property
    def is_expired(self):
        now = timezone.localtime()
        return self.specific_date == now.date() and self.end_time <= now.time()

    def __str__(self):
        return f"Dr. {self.doctor.get_full_name()} — {self.specific_date.strftime('%b %d, %Y')} {self.start_time.strftime('%I:%M %p')}–{self.end_time.strftime('%I:%M %p')}"


class DoctorScheduleSettings(models.Model):
    """Per-doctor booking rules that govern how bookable time slots are
    derived from their Schedule blocks. One row per doctor, created lazily
    via for_doctor() the first time it's needed — doctors without a row yet
    behave as if these are all still at their defaults."""
    DURATION_CHOICES = [(15, '15 min'), (30, '30 min'), (45, '45 min'), (60, '60 min')]
    BUFFER_CHOICES = [(0, 'No buffer'), (5, '5 min'), (10, '10 min'), (15, '15 min')]

    doctor = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='schedule_settings', limit_choices_to={'role': 'doctor'}
    )
    appointment_duration_minutes = models.PositiveSmallIntegerField(
        choices=DURATION_CHOICES, default=30
    )
    buffer_minutes = models.PositiveSmallIntegerField(
        choices=BUFFER_CHOICES, default=0
    )
    # None = unlimited bookings per day.
    max_bookings_per_day = models.PositiveIntegerField(null=True, blank=True)
    # How many days in advance patients may book / staff may see availability.
    advance_booking_days = models.PositiveIntegerField(default=60)
    # Minimum notice (in hours) required before a bookable slot.
    min_notice_hours = models.PositiveIntegerField(default=4)
    # Cache guard so sync_generated_schedule_for_doctor() only does real work
    # once per doctor per day from the lazy page-load triggers.
    last_synced_date = models.DateField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @classmethod
    def for_doctor(cls, doctor):
        obj, _ = cls.objects.get_or_create(doctor=doctor)
        return obj

    def __str__(self):
        return f"Schedule settings for Dr. {self.doctor.get_full_name()}"


class ScheduleTemplate(models.Model):
    """A doctor's recurring weekly availability block (e.g. every Monday
    9:00-12:00). Not directly bookable — services.sync_generated_schedule_for_doctor()
    materializes these into real Schedule rows for upcoming dates."""
    WEEKDAY_CHOICES = [
        (0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'),
        (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday'),
    ]

    doctor     = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='schedule_templates', limit_choices_to={'role': 'doctor'}
    )
    weekday    = models.PositiveSmallIntegerField(choices=WEEKDAY_CHOICES)
    start_time = models.TimeField()
    end_time   = models.TimeField()

    class Meta:
        ordering = ['weekday', 'start_time']

    def __str__(self):
        return f"Dr. {self.doctor.get_full_name()} — {self.get_weekday_display()} {self.start_time.strftime('%I:%M %p')}–{self.end_time.strftime('%I:%M %p')}"


class ScheduleException(models.Model):
    """Marker-only model. A row's presence means this doctor+date was
    manually adjusted (through the existing per-date Add/Edit/Delete tools)
    and must never be auto-generated/regenerated by the weekly template
    sync, regardless of whether the date currently has zero or several
    Schedule rows."""
    doctor     = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='schedule_exceptions', limit_choices_to={'role': 'doctor'}
    )
    date       = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('doctor', 'date')

    def __str__(self):
        return f"Adjusted availability — Dr. {self.doctor.get_full_name()} on {self.date.strftime('%b %d, %Y')}"


class AppointmentPatientDetails(models.Model):
    """Snapshot of the patient details entered on the booking form at the
    moment the appointment is confirmed (Patient Details step).

    DATA ISOLATION — This is the ONLY destination for appointment form data:
    These fields are intentionally kept completely separate from the live
    CustomUser / PatientProfile, because a patient may book an appointment
    on behalf of a family member or dependent (e.g. a sibling, parent, or
    child). The person being booked is not necessarily the account owner.

    The booking flow must NEVER write these fields back to CustomUser or
    PatientProfile. The logged-in user's account information (name, email,
    profile) must remain completely unchanged by the booking process.

    This row provides a durable, immutable per-appointment record of who
    the appointment was booked for, independent of any future changes to
    either the account owner's profile or a separate patient profile.
    """
    GENDER_CHOICES = [('M', 'Male'), ('F', 'Female')]

    RELATIONSHIP_CHOICES = [
        ('Self', 'Self'),
        ('Mother', 'Mother'),
        ('Father', 'Father'),
        ('Sibling', 'Sibling'),
        ('Child', 'Child'),
        ('Spouse', 'Spouse'),
        ('Other', 'Other'),
    ]

    appointment   = models.OneToOneField(
        'Appointment', on_delete=models.CASCADE, related_name='patient_details'
    )
    first_name    = models.CharField(max_length=150)
    middle_name   = models.CharField(max_length=150, blank=True)
    last_name     = models.CharField(max_length=150)
    date_of_birth = models.DateField()
    gender        = models.CharField(max_length=1, choices=GENDER_CHOICES)
    address       = models.TextField()
    mobile_number = models.CharField(max_length=20)
    email         = models.EmailField(blank=True)
    chief_complaint = models.TextField(
        help_text='Reason for booking / chief complaint, shown to the assigned doctor.'
    )
    relationship  = models.CharField(
        max_length=50, blank=True, default='Self',
        help_text="Relationship of the actual patient to the account holder. "
                  "'Self' means the booking is for the account owner."
    )
    terms_accepted_at = models.DateTimeField()

    created_at = models.DateTimeField(auto_now_add=True)

    def full_name(self):
        parts = [self.first_name, self.middle_name, self.last_name]
        return ' '.join(p for p in parts if p)

    def __str__(self):
        return f"Patient details for appointment #{self.appointment_id}"


class Appointment(models.Model):
    STATUS_CHOICES = [
        ('Pending Assignment',  'Pending Assignment'),
        ('Scheduled',          'Scheduled'),
        ('Confirmed',          'Confirmed'),
        ('Completed',          'Completed'),
        ('Cancelled',          'Cancelled'),
        ('No-Show',            'No-Show'),
        ('Rescheduled',        'Rescheduled'),
        ('Pending Reschedule', 'Pending Reschedule'),
    ]
    patient          = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='patient_appointments', limit_choices_to={'role': 'patient'}
    )
    doctor           = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='doctor_appointments', limit_choices_to={'role': 'doctor'}
    )
    secretary        = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
        null=True, blank=True, related_name='secretary_appointments',
        limit_choices_to={'role': 'secretary'}
    )
    appointment_date = models.DateField()
    # Null while the appointment is awaiting a time assignment from staff
    # (status == 'Pending Time Assignment'). Patients only pick a date when
    # booking or requesting a reschedule; the doctor or secretary assigns
    # the actual time afterward, which is when this gets filled in.
    appointment_time = models.TimeField(null=True, blank=True)
    # Snapshot of the doctor's appointment_duration_minutes setting at the
    # moment staff assigned a time, so changing the doctor's default later
    # never retroactively changes an already-assigned appointment's length.
    # Null (unassigned, or assigned before this field existed) means "use
    # the doctor's current DoctorScheduleSettings default" wherever a
    # duration is needed.
    duration_minutes = models.PositiveIntegerField(null=True, blank=True)
    status           = models.CharField(max_length=30, choices=STATUS_CHOICES, default='Pending Assignment')
    reason           = models.TextField(blank=True)

    # When a patient requests a reschedule, the original date/time/reason stay
    # untouched (status flips to 'Pending Reschedule') and the requested new
    # date is held here until staff approves or rejects the request.
    # requested_time is no longer set by the patient (date-only requests) but
    # stays on the model since an approved request still needs to carry a
    # time once staff assigns one.
    requested_date   = models.DateField(null=True, blank=True)
    requested_time   = models.TimeField(null=True, blank=True)
    requested_reason = models.TextField(blank=True)

    created_at       = models.DateTimeField(auto_now_add=True)
    updated_at       = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['appointment_date', TIME_NULLS_FIRST]
        indexes = [
            models.Index(fields=['status']),
            models.Index(fields=['appointment_date']),
            models.Index(fields=['doctor', 'appointment_date']),
        ]

    # Non-terminal statuses — the appointment is still awaiting some action
    # (time assignment, check-in, staff approval, etc.) rather than resolved.
    # Shared by has_active_appointment() below and by every role's
    # appointment-list view, which uses it to keep past-dated appointments
    # that were never closed out from lingering in the active/pending tabs.
    ACTIVE_STATUSES = [
        'Pending Assignment',
        'Scheduled',
        'Confirmed',
        'Rescheduled',
        'Pending Reschedule',
    ]

    @property
    def needs_time_assignment(self):
        return self.status == 'Pending Assignment'

    @property
    def can_resend_reminder(self):
        """Whether staff can manually re-send the day-before reminder email —
        mirrors the automated reminder command's own eligibility (upcoming,
        not yet resolved), just triggerable on demand instead of only the
        night before."""
        return self.status in ('Scheduled', 'Confirmed', 'Rescheduled') and self.appointment_date >= timezone.localdate()

    @classmethod
    def has_active_appointment(cls, patient):
        """Check if a patient has any active/upcoming appointment.
        Active statuses are those that prevent booking a new appointment:
        - Pending Assignment (awaiting staff to assign time)
        - Scheduled (assigned date/time, awaiting check-in)
        - Confirmed (patient has checked in, in progress)
        - Rescheduled (rescheduled appointment, still active)
        - Pending Reschedule (waiting for staff to approve reschedule)

        Patients can only book new appointments once their previous one reaches:
        - Completed (consultation finished)
        - Cancelled (patient or staff cancelled)
        """
        return cls.objects.filter(
            patient=patient,
            status__in=cls.ACTIVE_STATUSES
        ).exists()

    def __str__(self):
        return f"{self.patient.get_full_name()} + Dr. {self.doctor.get_full_name()} on {self.appointment_date} [{self.status}]"
