# Generated by hand on 2026-06-26
#
# Schedule used to be recurring-weekly (day_of_week applied to every
# matching weekday forever). It's now date-specific: each Schedule row
# is one slot block on one actual calendar date. Per project decision,
# old recurring rows are wiped rather than converted/migrated forward
# into dated rows, so this runs a data migration to delete them before
# the schema change — avoids needing to invent a default specific_date
# for rows that have no natural one.

from django.db import migrations, models


def wipe_old_schedules(apps, schema_editor):
    Schedule = apps.get_model('appointments', 'Schedule')
    Schedule.objects.all().delete()


def noop_reverse(apps, schema_editor):
    # Old recurring rows are gone for good; nothing to restore on reverse.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_requested_date_and_more'),
    ]

    operations = [
        migrations.RunPython(wipe_old_schedules, noop_reverse),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='schedule',
            name='specific_date',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('doctor', 'specific_date', 'start_time')},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['specific_date', 'start_time']},
        ),
    ]
