# Generated by Django 4.2.28 on 2026-07-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointment_workflow_redesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentpatientdetails',
            name='relationship',
            field=models.CharField(blank=True, default='Self', help_text="Relationship of the actual patient to the account holder. 'Self' means the booking is for the account owner.", max_length=50),
        ),
    ]
