# Generated by Django 4.2.28 on 2026-07-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_appointment_no_show_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['appointment_date', models.OrderBy(models.F('appointment_time'), nulls_first=True)]},
        ),
    ]
