# Generated by Django 5.0.12 on 2026-08-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_alter_appointment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentpatientdetails',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
